version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
        deploy:
            provider: elasticbeanstalk
            region: "us-east-2"
            app: "docker_react"
            env: "DockerReact-env"
            bucket_name: "elasticbeanstalk-us-east-2-493059561792"
            bucket_path: "docker_react"
            on:
              branch: master
            access_key_id: $AWS_ACCESS_KEY
            secret_access_key: $AWS_SECRET_KEY
           
            http://dockerreact-env.eba-ftpzsvya.us-east-2.elasticbeanstalk.com/   